# TheJailBreakShow Configuration

# Language setting (en, he, etc.)
language: "en"

# Teams Configuration
teams:
  max-guards: 2
  default-guards: 1
  guard-prisoner-ratio: 2  # 1 guard for every 2 prisoners

# Rounds Configuration
rounds:
  guard-challenge-interval: 3  # Guard challenge occurs every 3 rounds
  free-day-round: 6
  reset-after-round: 12
  round-duration: 6000
  auto-progress: true

# Free Day Configuration
free-day:
  duration: 300 # in seconds

# Currency Configuration
currency:
  initial-gold: 100
  kill-reward:
    prisoner-kills-guard: 50
    guard-kills-prisoner: 10

# HUD Configuration
hud:
  update-interval: 20 # in ticks

# Guard Challenges Configuration
guard-challenges:
  speed:
    effect: "SPEED"
    duration: 30 # in seconds
    amplifier: 1 # effect level (0 = level 1)
    cost: 100
  strength:
    effect: "INCREASE_DAMAGE"
    duration: 20
    amplifier: 0
    cost: 150
  jump:
    effect: "JUMP"
    duration: 25
    amplifier: 1
    cost: 75